title: tree

author: arthur

links:
  github: https://github.com/wujun234
  
favicon: /iconbrouette.jpg

# valine 
valine:
    # 评论
    enableComment: false 
    # 阅读量
    enableCounter: true
    # valine appID
    appID:
    # valine appKey
    appKey:
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: true

# 底部版权开始年份
siteStartYear: 2021
searchEngine: https://www.google.com/search?q=
homeHost: brouettelover.github.io

tags: true
categories: true

# 左侧导航栏，用文件名还是文章名
sidebar:
  # usePostTitle 为 true 用文章名，不填或为 false 用文件名
  usePostTitle: false
